# this has some defaults for quick startup
# you still need to define the oauth properties
# for production, you should definitely override the settings with localhost
# to add/change properties use the command line argument:
#      --spring.config.additional-locations=<additional yml file>
server:
  port: 27778
custom:
  metadataServer: http://localhost:2777
