spring.security.oauth2.client.registration.test.clientId=test-client-id
spring.security.oauth2.client.registration.test.clientSecret=test-client-secret
spring.security.oauth2.client.registration.test.provider=test
spring.security.oauth2.client.registration.test.authorizationGrantType=authorization_code
spring.security.oauth2.client.registration.test.redirectUri=http://localhost:8080/login/oauth2/code/test
spring.security.oauth2.client.provider.test.authorizationUri=http://localhost:8080/oauth2/authorize
spring.security.oauth2.client.provider.test.tokenUri=http://localhost:8080/oauth2/token
spring.security.oauth2.client.provider.test.userInfoUri=http://localhost:8080/userinfo
spring.security.oauth2.client.provider.test.userNameAttribute=id