meta.security.oauth2.client.registration.test.clientId=test-client-id
meta.security.oauth2.client.registration.test.clientSecret=test-client-secret
meta.security.oauth2.client.registration.test.provider=test
meta.security.oauth2.client.registration.test.authorizationGrantType=authorization_code
meta.security.oauth2.client.registration.test.redirectUri=http://localhost:8080/login/oauth2/code/test
meta.security.oauth2.client.provider.test.authorizationUri=http://localhost:8080/oauth2/authorize
meta.security.oauth2.client.provider.test.tokenUri=http://localhost:8080/oauth2/token
meta.security.oauth2.client.provider.test.userInfoUri=http://localhost:8080/userinfo
meta.security.oauth2.client.provider.test.userNameAttribute=id
logging.level.org.springframework.security=DEBUG