services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  wildstore-meta:
    image: ghcr.io/sjsu-cs-systems-group/wildstore/wildstore-meta:deploy
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./oauth.yml:/app/oauth.yml:ro
    environment:
      - spring.config.additional-location=file:/app/oauth.yml
      - server.port=8080
      - spring.data.mongodb.uri=mongodb://mongo:27017/wildfire
      - custom.fileServer=http://wildstore-fileserve:27778
      - custom.frontendUrl=http://localhost:8080
    depends_on:
      - mongo

  wildstore-fileserve:
    image: ghcr.io/sjsu-cs-systems-group/wildstore/wildstore-fileserve:deploy
    restart: unless-stopped
    ports:
      - "27778:27778"
    environment:
      - custom.metadataServer=http://wildstore-meta:8080
    depends_on:
      - wildstore-meta

volumes:
  mongo-data:
