import React, { useEffect } from 'react';
import Select from 'react-select'
import { useState } from "react";
import { useDispatch } from "react-redux";
import { addQuery } from '../../redux/filterSlice';
import Predicate from '../predicate/predicate';
import { useSelector } from 'react-redux';

const Filter = () => {

    const dispatch = useDispatch();

    const variableList = useSelector(state => state.metadataReducer.descriptions);

    // const variableList = ['AACD', 'ACGRDFLX', 'ACHFX', 'ACLHF', 'ACLWDNB', 'ACLWDNBC', 'ACLWDNT', 'ACLWDNTC', 'ACLWUPB', 'ACLWUPBC', 'ACLWUPT', 'ACLWUPTC', 'ACRUNOFF', 'ACSNOM', 'ACSNOW', 'ACSWDNB', 'ACSWDNBC', 'ACSWDNT', 'ACSWDNTC', 'ACSWUPB', 'ACSWUPBC', 'ACSWUPT', 'ACSWUPTC', 'AL', 'ALB', 'ALBBCK', 'ALBEDO', 'ALBEDO12M', 'ALBOLD', 'ALD2', 'ALDX', 'ALPHA_VPRM', 'ALT', 'AOD2D_OUT', 'AOD_OUT', 'APAR', 'AREA2D', 'ATOP2D_OUT', 'AVG_FUEL_FRAC', 'Ap', 'BATHYMETRY_FLAG', 'BBB', 'BC1', 'BC2', 'BENZENE', 'BGAP', 'BIOMT_PAR', 'Bp', 'C1F', 'C1H', 'C2F', 'C2H', 'C3F', 'C3H', 'C4F', 'C4H', 'CANFRA', 'CANHFX', 'CANICE', 'CANLIQ', 'CANQFX', 'CANWAT', 'CAN_TOP', 'CF1', 'CF2', 'CF3', 'CFN', 'CFN1', 'CH', 'CH4', 'CHB', 'CHB2', 'CHLEAF', 'CHSTAR', 'CHUC', 'CHV', 'CHV2', 'CLAT', 'CLAYFRAC', 'CLDFRA', 'CLDFRA2', 'CLONG', 'CM', 'CN2O5', 'CO', 'CON', 'COSALPHA', 'COSALPHA_U', 'COSALPHA_V', 'COSZEN', 'CPLMASK', 'CRES', 'CROPCAT', 'CTOPO', 'CTOPO2', 'CUF', 'CVF', 'DD', 'DMS_0', 'DN', 'DNW', 'DRYDEPVEL', 'DRY_DEP_LEN', 'DTAUX3D', 'DTAUY3D', 'DTS', 'DTSEPS', 'DUSFCG', 'DUST_1', 'DUST_2', 'DUST_3', 'DUST_4', 'DUST_5', 'DVSFCG', 'DX2D', 'DZDXF', 'DZDYF', 'DZS', 'E', 'EAH', 'EBIO_API', 'EBIO_ISO', 'ECAN', 'EDIR', 'EDMF_A', 'EDMF_ENT', 'EDMF_QC', 'EDMF_QT', 'EDMF_THL', 'EDMF_W', 'EDT_OUT', 'EL_MYJ', 'EL_MYNN', 'EL_PBL', 'EMISS', 'EMIT_PAR', 'EQUILd_FM', 'EQUILw_FM', 'EROD', 'ETAC', 'ETAE', 'ETH', 'ETHA', 'ETOH', 'ETRAN', 'EVAPPROD', 'EVB', 'EVC', 'EVG', 'EastWind', 'F', 'FACD', 'FASTCP', 'FCANHFX', 'FCANQFX', 'FCX', 'FGIP', 'FGRNHFX', 'FGRNQFX', 'FIRA', 'FIRE_AREA', 'FIRE_HFX', 'FLINEINT', 'FLINEINT2', 'FMCG2D', 'FMCGLH2D', 'FMC_COV', 'FMC_EQUI', 'FMC_G', 'FMC_GC', 'FMC_GC_B', 'FMC_TEND', 'FMEP', 'FMOIST_LASTTIME', 'FMOIST_NEXTTIME', 'FNDALBSI', 'FNDICEDEPTH', 'FNDSNOWH', 'FNDSNOWSI', 'FNDSOILW', 'FNDWI', 'FNM', 'FNP', 'FORM', 'FRC_URB2D', 'FSA', 'FUEL_FRAC', 'FUEL_FRAC_BURNT', 'FUEL_TIME', 'FVEG', 'FWET', 'FWH', 'FXLAT', 'FXLONG', 'FZ0', 'F_INT', 'F_LINEINT', 'F_LINEINT2', 'F_ROS', 'F_ROS0',
    //     'F_ROS11', 'F_ROS12', 'F_ROS13', 'F_ROS21', 'F_ROS23', 'F_ROS31', 'F_ROS32', 'F_ROS33', 'F_ROSX', 'F_ROSY', 'GAMN2O5', 'GCX', 'GDD', 'GHB', 'GHT', 'GHV', 'GLW', 'GOT_VAR_SSO', 'GPP', 'GRAIN', 'GRAUPELNC', 'GRDFLX', 'GREENFRAC', 'GRNHFX', 'GRNQFX', 'GSW', 'H2O', 'HAILNC', 'HFX', 'HFX_FDDA', 'HFX_FORCE', 'HFX_FORCE_TEND', 'HGT', 'HGT_M', 'HGT_SHAD', 'HGT_U', 'HGT_V', 'HH', 'HNO3', 'HONO', 'H_DIABATIC', 'ICN_DIAG', 'IJ-AVG-S__ACET', 'IJ-AVG-S__ALD2', 'IJ-AVG-S__ALK4', 'IJ-AVG-S__ASOA1', 'IJ-AVG-S__ASOA2', 'IJ-AVG-S__ASOA3', 'IJ-AVG-S__ASOAN', 'IJ-AVG-S__ASOG1', 'IJ-AVG-S__ASOG2', 'IJ-AVG-S__ASOG3', 'IJ-AVG-S__BCPI', 'IJ-AVG-S__BCPO', 'IJ-AVG-S__BENZ', 'IJ-AVG-S__Br', 'IJ-AVG-S__Br2', 'IJ-AVG-S__BrNO2', 'IJ-AVG-S__BrNO3', 'IJ-AVG-S__BrO', 'IJ-AVG-S__C2H6', 'IJ-AVG-S__C3H8', 'IJ-AVG-S__CH2Br2', 'IJ-AVG-S__CH2O', 'IJ-AVG-S__CH3Br', 'IJ-AVG-S__CHBr3', 'IJ-AVG-S__CO', 'IJ-AVG-S__DMS', 'IJ-AVG-S__DST1', 'IJ-AVG-S__DST2', 'IJ-AVG-S__DST3', 'IJ-AVG-S__DST4', 'IJ-AVG-S__GLYC', 'IJ-AVG-S__H2O2', 'IJ-AVG-S__HAC', 'IJ-AVG-S__HBr', 'IJ-AVG-S__HNO2', 'IJ-AVG-S__HNO3', 'IJ-AVG-S__HNO4', 'IJ-AVG-S__HOBr', 'IJ-AVG-S__IEPOX', 'IJ-AVG-S__ISOA1', 'IJ-AVG-S__ISOA2', 'IJ-AVG-S__ISOA3', 'IJ-AVG-S__ISOG1', 'IJ-AVG-S__ISOG2', 'IJ-AVG-S__ISOG3', 'IJ-AVG-S__ISOP', 'IJ-AVG-S__ISOPN', 'IJ-AVG-S__LIMO', 'IJ-AVG-S__MACR', 'IJ-AVG-S__MAP', 'IJ-AVG-S__MEK', 'IJ-AVG-S__MMN', 'IJ-AVG-S__MOBA', 'IJ-AVG-S__MP', 'IJ-AVG-S__MPN', 'IJ-AVG-S__MSA', 'IJ-AVG-S__MTPA', 'IJ-AVG-S__MTPO', 'IJ-AVG-S__MVK', 'IJ-AVG-S__N2O5', 'IJ-AVG-S__NAP', 'IJ-AVG-S__NH3', 'IJ-AVG-S__NH4', 'IJ-AVG-S__NIT', 'IJ-AVG-S__NITs', 'IJ-AVG-S__NO', 'IJ-AVG-S__NO2', 'IJ-AVG-S__NO3', 'IJ-AVG-S__O3', 'IJ-AVG-S__OPOA1', 'IJ-AVG-S__OPOA2', 'IJ-AVG-S__OPOG1', 'IJ-AVG-S__OPOG2', 'IJ-AVG-S__PAN', 'IJ-AVG-S__PMN', 'IJ-AVG-S__POA1', 'IJ-AVG-S__POA2', 'IJ-AVG-S__POG1', 'IJ-AVG-S__POG2', 'IJ-AVG-S__PPN', 'IJ-AVG-S__PROPNN', 'IJ-AVG-S__PRPE', 'IJ-AVG-S__R4N2', 'IJ-AVG-S__RCHO', 'IJ-AVG-S__RIP', 'IJ-AVG-S__SALA', 'IJ-AVG-S__SALC', 'IJ-AVG-S__SO2', 'IJ-AVG-S__SO4', 'IJ-AVG-S__SO4s', 'IJ-AVG-S__TOLU', 'IJ-AVG-S__TSOA0', 'IJ-AVG-S__TSOA1', 'IJ-AVG-S__TSOA2', 'IJ-AVG-S__TSOA3', 'IJ-AVG-S__TSOG0', 'IJ-AVG-S__TSOG1', 'IJ-AVG-S__TSOG2', 'IJ-AVG-S__TSOG3', 'IJ-AVG-S__XYLE', 'IMPERV', 'IOLE', 'IRB', 'IRC', 'IRG', 'ISCHAP', 'ISEEDARRAY_SPP_CONV', 'ISEEDARRAY_SPP_LSM', 'ISEEDARRAY_SPP_PBL', 'ISEEDARR_RAND_PERTURB', 'ISEEDARR_SKEBS', 'ISEEDARR_SPPT', 'ISLTYP', 'ISNOW', 'ISOP', 'ISPD', 'ITIMESTEP', 'IVGTYP', 'I_ACLWDNB', 'I_ACLWDNBC', 'I_ACLWDNT', 'I_ACLWDNTC', 'I_ACLWUPB', 'I_ACLWUPBC', 'I_ACLWUPT', 'I_ACLWUPTC', 'I_ACSWDNB', 'I_ACSWDNBC', 'I_ACSWDNT', 'I_ACSWDNTC', 'I_ACSWUPB', 'I_ACSWUPBC', 'I_ACSWUPT', 'I_ACSWUPTC', 'I_RAINC', 'I_RAINNC', 'KN2O5', 'KTOP_PLUME', 'LAI', 'LAI12M', 'LAI_VEGMASK', 'LAKEFLAG', 'LAKEMASK', 'LAKE_DEPTH', 'LAKE_DEPTH_FLAG', 'LAMBDA_VPRM', 'LANDMASK', 'LANDSEA', 'LANDUSEF', 'LAP_HGT', 'LAT', 'LAT_LL_D', 'LAT_LL_T', 'LAT_LL_U', 'LAT_LL_V',
    //     'LAT_LR_D', 'LAT_LR_T', 'LAT_LR_U', 'LAT_LR_V', 'LAT_UL_D', 'LAT_UL_T', 'LAT_UL_U', 'LAT_UL_V', 'LAT_UR_D', 'LAT_UR_T', 'LAT_UR_U', 'LAT_UR_V', 'LFMASS', 'LFM_Chamise_New', 'LFM_Chamise_Old', 'LFM_Manzanita_New', 'LFN', 'LH', 'LH_FORCE', 'LH_FORCE_TEND', 'LON', 'LON_LL_D', 'LON_LL_T', 'LON_LL_U', 'LON_LL_V', 'LON_LR_D', 'LON_LR_T', 'LON_LR_U', 'LON_LR_V', 'LON_UL_D', 'LON_UL_T', 'LON_UL_U', 'LON_UL_V', 'LON_UR_D', 'LON_UR_T', 'LON_UR_U', 'LON_UR_V', 'LU_INDEX', 'LWDNB', 'LWDNBC', 'LWDNT', 'LWDNTC', 'LWUPB', 'LWUPBC', 'LWUPT', 'LWUPTC', 'MAPFAC_M', 'MAPFAC_MX', 'MAPFAC_MY', 'MAPFAC_U', 'MAPFAC_UX', 'MAPFAC_UY', 'MAPFAC_V', 'MAPFAC_VX', 'MAPFAC_VY', 'MAXMF', 'MAX_MSFTX', 'MAX_MSFTY', 'MAX_MSTFX', 'MAX_MSTFY', 'MEOH', 'MF_VX_INV', 'MGLY', 'MM', 'MU', 'MUB', 'N2O', 'N2O5', 'NC_DIAG', 'NDVI', 'NDWI', 'NEE', 'NEST_POS', 'NFUEL_CAT', 'NH3', 'NH4', 'NO', 'NO2', 'NOAHRES', 'NOX', 'NPP', 'NR', 'NUPDRAFT', 'NVOL', 'NorthEastWind', 'NorthWestWind', 'NorthWind', 'O2_column_density', 'O3', 'O3_column_DU', 'O3_column_density', 'OA1', 'OA2', 'OA3', 'OA4', 'OC1', 'OC2', 'OL1', 'OL2', 'OL3', 'OL4', 'OLE', 'OLR', 'OPEN', 'P', 'P00', 'P10', 'P25', 'PAR', 'PB', 'PBLDEPTH__PBL-M', 'PBLH', 'PC', 'PCB', 'PEC', 'PGS', 'PH', 'PHB', 'PHISC', 'PHIWC', 'PHOTR201', 'PHOTR202', 'PHOTR203', 'PHOTR204', 'PM10', 'PM2_5_DRY', 'PMC', 'PMFINE', 'PMSL', 'PNO3', 'POC', 'POTEVP', 'PRATEC', 'PRECIP', 'PRECIPA', 'PREC_ACC_C', 'PREC_ACC_NC', 'PRES', 'PSFC', 'PSFC_OLD', 'PSN', 'PSO4', 'PV', 'P_HYD', 'P_STRAT', 'P_TOP', 'Q2', 'Q2B', 'Q2V', 'Q2_OLD', 'QCLOUD', 'QFX', 'QGRAUP', 'QICE', 'QIN', 'QKE', 'QNICE', 'QNRAIN', 'QRAIN', 'QRFS', 'QSLAT', 'QSNOW', 'QSNOWXY', 'QSPRINGS', 'QVAPOR', 'QV_BASE', 'QV_UPSTREAM_X', 'QV_UPSTREAM_X_TEND', 'QV_UPSTREAM_Y', 'QV_UPSTREAM_Y_TEND', 'RAD_VPRM', 'RAIN', 'RAINC', 'RAINCV', 'RAINCV_B', 'RAINNC', 'RAINNCV', 'RAINPROD', 'RAINSH', 'RAIN_OLD', 'RDN', 'RDNW', 'RDX', 'RDY', 'RECH', 'RESM', 'RESP_VPRM', 'RH', 'RHOSN', 'RHOSNF', 'RH_FIRE', 'ROS', 'ROUGH_COR', 'RQVFRTEN', 'RSSHA', 'RSSUN', 'RTHFRTEN', 'RTMASS', 'RUNSB', 'RUNSF', 'R_0', 'SAC', 'SAG',
    //     'SANDFRAC', 'SAV', 'SAVE_TOPO_FROM_REAL', 'SCB_DOM', 'SCT_DOM', 'SEAICE', 'SEAS_1', 'SEAS_2', 'SEAS_3', 'SEAS_4', 'SEED1', 'SEED2', 'SFROFF', 'SH2O', 'SHB', 'SHC', 'SHDMAX', 'SHDMIN', 'SHG', 'SINALPHA', 'SINALPHA_U', 'SINALPHA_V', 'SKINTEMP', 'SLOPECAT', 'SLPX', 'SLPY', 'SM', 'SM000010', 'SM010040', 'SM040100', 'SM100200', 'SMCREL', 'SMCWTD', 'SMOIS', 'SMOIS_0', 'SMOIS_1', 'SMOIS_2', 'SMOIS_3', 'SMOIS_COR', 'SMSTAV', 'SNEQVO', 'SNICE', 'SNLIQ', 'SNOALB', 'SNOPCX', 'SNOW', 'SNOWC', 'SNOWFALLAC', 'SNOWH', 'SNOWNC', 'SNOW_ACC_NC', 'SNU', 'SO2', 'SOILCAT', 'SOILCBOT', 'SOILCTOP', 'SOILHGT', 'SOILT1', 'SOILTB', 'SOILTEMP', 'SOIL_LAYERS', 'SR', 'SST', 'SSTSK', 'SST_INPUT', 'SSWDN', 'SSWUP', 'ST', 'ST000010', 'ST010040', 'ST040100', 'ST100200', 'STBLCP', 'STEPAVE_COUNT', 'STEP_NUMBER', 'STMASS', 'SULF', 'SWDDIF', 'SWDDIR', 'SWDDNI', 'SWDNB', 'SWDNBC', 'SWDNT', 'SWDNTC', 'SWDOWN', 'SWNORM', 'SWUPB', 'SWUPBC', 'SWUPT', 'SWUPTC', 'SouthEastWind', 'SouthWestWind', 'SouthWind', 'T', 'T00', 'T2', 'T2B', 'T2V', 'T2_OLD', 'TAH', 'TAUSS', 'TD', 'TERP', 'TFLAG', 'TG', 'TGB', 'TGV', 'TH2', 'THIS_IS_AN_IDEAL_RUN', 'THM', 'TH_UPSTREAM_X', 'TH_UPSTREAM_X_TEND', 'TH_UPSTREAM_Y', 'TH_UPSTREAM_Y_TEND', 'TIGN_G', 'TIGN_IN', 'TIME-SER__AIRDEN', 'TIME-SER__OH', 'TISO', 'TKE', 'TKESFCF', 'TKE_MYJ', 'TKE_PBL', 'TLP', 'TLP_STRAT', 'TMN', 'TOL', 'TOPOSLPX', 'TOPOSLPY', 'TR', 'TRAD', 'TSK', 'TSK_FORCE', 'TSK_FORCE_TEND', 'TSLB', 'TSLB_0', 'TSLB_1', 'TSLB_2', 'TSLB_3', 'TSM_K', 'TSM_V', 'TSNO', 'TSWDN', 'TSWUP', 'TT', 'TV', 'T_BASE', 'T_INIT', 'Times', 'U', 'U10', 'U10E', 'UAH', 'UDROFF', 'UF', 'UNIT_FXLAT', 'UNIT_FXLONG', 'UNK', 'UNR', 'UOCE', 'URB_PARAM', 'UST', 'UST_T', 'UU', 'U_BASE', 'U_FRAME', 'U_G', 'U_G_TEND', 'U_UPSTREAM_X', 'U_UPSTREAM_X_TEND', 'U_UPSTREAM_Y', 'U_UPSTREAM_Y_TEND', 'V', 'V10', 'V10E', 'VAH', 'VAR', 'VAR_SSO', 'VEGCAT', 'VEGFRA', 'VF', 'VOCE', 'VOC_INV', 'VV', 'V_BASE', 'V_FRAME', 'V_G', 'V_G_TEND', 'V_UPSTREAM_X', 'V_UPSTREAM_X_TEND', 'V_UPSTREAM_Y', 'V_UPSTREAM_Y_TEND', 'W', 'WA', 'WATER_DEPTH', 'WGAP', 'WOOD', 'WSLAKE', 'WT', 'WZ0',
    //     'W_SUBS', 'W_SUBS_TEND', 'WestWind', 'XICEM', 'XLAND', 'XLAT', 'XLAT_C', 'XLAT_M', 'XLAT_U', 'XLAT_V', 'XLONG', 'XLONG_C', 'XLONG_M', 'XLONG_U', 'XLONG_V', 'XMB_SHALLOW', 'XSAI', 'XTIME', 'XYL', 'YCLNO2', 'YYYY', 'Z0', 'ZETATOP', 'ZF', 'ZNT', 'ZNU', 'ZNW', 'ZS', 'ZSF', 'ZSNSO', 'ZWT', 'Z_BASE', 'Z_FORCE', 'aa', 'ac0', 'acbzo2', 'accumulated_precipitation_amount', 'acet', 'aceto2', 'acetol', 'acetp', 'aco3', 'air_dens_data', 'air_relative_humidity_2m', 'air_temperature_2m', 'ald', 'alknit', 'alko2', 'alkooh', 'antha', 'apin', 'b', 'bb', 'bcary', 'benzene', 'benzo2', 'benzooh', 'bepomuc', 'bigald1', 'bigald2', 'bigald3', 'bigald4', 'bigalk', 'bigene', 'bpin', 'bytev', 'bytevar', 'bzald', 'bzoo', 'bzooh', 'c10h16', 'c2h2', 'c2h4', 'c2h5oh', 'c2h6', 'c3h6', 'c3h6ooh', 'c3h8', 'c6h5o2', 'c6h5ooh', 'cbh', 'cc', 'cd', 'ce', 'ch', 'ch3cn', 'ch3cooh', 'ch3o2', 'ch3oh', 'ch3ooh', 'ch4', 'charv', 'charvar', 'chebev_ac', 'chebev_bc', 'clai', 'claj', 'co', 'concs', 'corn', 'cres', 'csl', 'd', 'date', 'datetime', 'dcb', 'dd', 'dem', 'dicarbo2', 'dms', 'doublev', 'doublevar', 'dvel_o3', 'eastward_10m_wind', 'eci', 'ecj', 'eneo2', 'eo', 'eo2', 'eooh', 'etf', 'eth', 'eto2', 'etooh', 'evh', 'evt', 'f', 'fbfm13', 'fire_area', 'floatv', 'floatvar', 'gly', 'glyald', 'h2', 'h2o2', 'hc3', 'hc5', 'hc8', 'hcho', 'hcl', 'hcn', 'hcooh', 'hmprop', 'hmpropo2', 'hno3', 'hno4', 'ho', 'ho2', 'hoch2oo', 'honitr', 'hono', 'hpald', 'hydrald', 'iepox', 'ila', 'iso', 'iso2', 'isooh', 'isopao2', 'isopbo2', 'isopn', 'isopnita', 'isopnitb', 'isopnooh', 'isopr', 'isrb', 'j_1c4h9ono2_xsqy', 'j_2c4h9ono2_xsqy', 'j_acrol_xsqy', 'j_amine_xsqy', 'j_biacetyl_xsqy', 'j_bnit_a_xsqy', 'j_bnit_b_xsqy', 'j_br2_xsqy', 'j_brcl_xsqy', 'j_brno2_xsqy', 'j_brno_xsqy', 'j_bro_xsqy', 'j_brono2_a_xsqy', 'j_brono2_b_xsqy', 'j_brono_a_xsqy', 'j_brono_b_xsqy', 'j_c2h5cho_xsqy', 'j_c2h5ono2_xsqy', 'j_ccl2f2_xsqy', 'j_ccl2o_xsqy', 'j_ccl3f_xsqy', 'j_ccl4_xsqy', 'j_cclfo_xsqy', 'j_cf2br2_xsqy', 'j_cf2brcf2br_xsqy', 'j_cf2brcl_xsqy', 'j_cf2clcf2chfcl_xsqy', 'j_cf2clcf2cl_xsqy', 'j_cf2clcfcl2_xsqy', 'j_cf2o_xsqy',
    //     'j_cf3br_xsqy', 'j_cf3cf2chcl2_xsqy', 'j_cf3cf2cl_xsqy', 'j_cf3chcl2_xsqy', 'j_cf3chfcl_xsqy', 'j_ch2o_m_xsqy', 'j_ch2o_r_xsqy', 'j_ch2ohch2ono2_xsqy', 'j_ch3br_xsqy', 'j_ch3ccl3_xsqy', 'j_ch3cf2cl_xsqy', 'j_ch3cfcl2_xsqy', 'j_ch3ch2ono2_xsqy', 'j_ch3cho_a_xsqy', 'j_ch3cho_b_xsqy', 'j_ch3cho_c_xsqy', 'j_ch3chono2ch3_xsqy', 'j_ch3cl_xsqy', 'j_ch3coch2ono2_xsqy', 'j_ch3coch3_xsqy', 'j_ch3cocoooh_xsqy', 'j_ch3cooh_xsqy', 'j_ch3coooh_xsqy', 'j_ch3ocl_xsqy', 'j_ch3ono2_xsqy', 'j_ch3ooh_xsqy', 'j_ch3oono2_xsqy', 'j_chbr3_xsqy', 'j_chcl3_xsqy', 'j_chclf2_xsqy', 'j_cl2_xsqy', 'j_clno2_xsqy', 'j_clo_a_xsqy', 'j_clo_b_xsqy', 'j_clono2_a_xsqy', 'j_clono2_b_xsqy', 'j_clono_xsqy', 'j_cloo_xsqy', 'j_cloocl_xsqy', 'j_gly_a_xsqy', 'j_gly_b_xsqy', 'j_gly_c_xsqy', 'j_glyald_a_xsqy', 'j_glyald_b_xsqy', 'j_glyald_c_xsqy', 'j_h2o2_xsqy', 'j_hcl_xsqy', 'j_hno2_xsqy', 'j_hno3_xsqy', 'j_hno4_xsqy', 'j_ho2_xsqy', 'j_hobr_xsqy', 'j_hoch2ooh_xsqy', 'j_hocl_xsqy', 'j_hyac_a_xsqy', 'j_hyac_b_xsqy', 'j_macr_xsqy', 'j_mek_xsqy', 'j_mgly_xsqy', 'j_mvk_xsqy', 'j_n2o5_a_xsqy', 'j_n2o5_b_xsqy', 'j_n2o_xsqy', 'j_nc3h7ono2_xsqy', 'j_no2_xsqy', 'j_no3_a_xsqy', 'j_no3_aq_a_xsqy', 'j_no3_aq_b_xsqy', 'j_no3_b_xsqy', 'j_nocl_xsqy', 'j_o1d_xsqy', 'j_o2_xsqy', 'j_o3p_xsqy', 'j_oclo_xsqy', 'j_pan_a_xsqy', 'j_pan_b_xsqy', 'j_perfluoro_xsqy', 'j_ppn_a_xsqy', 'j_ppn_b_xsqy', 'ket', 'l', 'lat', 'latitude', 'lev', 'limon', 'lon', 'longitude', 'longv', 'longvar', 'macr', 'malo2', 'mask', 'mbo', 'mbono3o2', 'mboo2', 'mboooh', 'mco3', 'mdialo2', 'mean_wtd_moisture_1000hr', 'mean_wtd_moisture_100hr', 'mean_wtd_moisture_10hr', 'mean_wtd_moisture_1hr', 'mek', 'meko2', 'mekooh', 'mgly', 'month', 'mpan', 'mvk', 'mvko2', 'mvkooh', 'myrc', 'n2o', 'n2o5', 'naai', 'naaj', 'nc4ch2oh', 'nc4cho', 'nh3', 'nh4ai', 'nh4aj', 'no', 'no2', 'no2_xs', 'no3', 'no3ai', 'no3aj', 'noa', 'northward_10m_wind', 'nterpo2', 'nterpooh', 'nu0', 'o', 'o1d', 'o1d_cb4', 'o2_xs', 'o3', 'o3_data', 'o3_xs', 'ol2', 'oli', 'olt', 'onit', 'onitr', 'op1', 'op2', 'open', 'ora1', 'ora2', 'orgalk1i', 'orgalk1j', 'orgaro1i', 'orgaro1j', 'orgaro2i', 'orgaro2j', 'orgba1i', 'orgba1j', 'orgba2i', 'orgba2j', 'orgba3i', 'orgba3j', 'orgba4i', 'orgba4j', 'orgole1i', 'orgole1j', 'orgpai', 'orgpaj', 'p25i', 'p25j', 'paa', 'pan', 'pbznit', 'pheno', 'pheno2', 'phenol', 'phenooh', 'po2', 'pro2', 'prooh', 'qke', 'qke_adv', 's', 'scalarv', 'seas', 'season_wes', 'seasonal_wes', 'shortv', 'shortvar', 'so2', 'so2_xs', 'so4ai', 'so4aj', 'soila', 'specname', 'sulf', 'surface_downwelling_shortwave_flux', 'temp_data', 'temps', 'tepomuc', 'terp2o2', 'terp2ooh', 'terpnit', 'terpo2', 'terpooh',
    //     'terprod1', 'terprod2', 'time', 'to2', 'tol', 'tolooh', 'tpan', 'tr17_1', 'tr17_2', 'tr17_3', 'tr17_4', 'tr17_5', 'tr17_6', 'tr17_7', 'tr17_8', 'trop_p', 'tt', 'tu', 'uu', 'vmr', 'vv', 'wc', 'wl', 'ww', 'x', 'xo2', 'xoh', 'xooh', 'xx', 'xyl', 'xylenes', 'xyleno2', 'xylenooh', 'xylol', 'xylolo2', 'xylolooh', 'y', 'yet_another_variable', 'yy', 'z_air_dens_data', 'z_o3_data', 'z_temp_data',
    //     'zz'];
    // const attributeList = ['ADAPT_DT_MAX', 'ADAPT_DT_MIN', 'ADAPT_DT_START', 'AERCU_FCT', 'AERCU_OPT', 'AER_ANGEXP_OPT', 'AER_ANGEXP_VAL', 'AER_AOD550_OPT', 'AER_AOD550_VAL', 'AER_ASY_OPT', 'AER_ASY_VAL', 'AER_OPT', 'AER_SSA_OPT', 'AER_SSA_VAL', 'AER_TYPE', 'AUTO_LEVELS_OPT', 'BLDT', 'BL_PBL_PHYSICS', 'BOTTOM-TOP_GRID_DIMENSION', 'BOTTOM-TOP_PATCH_END_STAG', 'BOTTOM-TOP_PATCH_END_UNSTAG', 'BOTTOM-TOP_PATCH_START_STAG', 'BOTTOM-TOP_PATCH_START_UNSTAG', 'BUCKET_J', 'BUCKET_MM', 'CDATE', 'CEN_LAT', 'CEN_LON', 'CLDOVRLP', 'CTIME', 'CUDT', 'CU_PHYSICS', 'Comment', 'Conventions', 'DAMPCOEF', 'DAMP_OPT', 'DFI_OPT', 'DIFF_6TH_FACTOR', 'DIFF_6TH_OPT', 'DIFF_6TH_SLOPEOPT', 'DIFF_6TH_THRESH', 'DIFF_OPT', 'DT', 'DTRAMP_MIN', 'DVEG', 'DX', 'DY', 'DYN_OPT', 'DZBOT', 'DZSTRETCH_S', 'DZSTRETCH_U', 'Delta_Lat', 'Delta_Lon', 'Description', 'ETAC', 'EXEC_ID', 'EndDate', 'End_Date', 'End_Time', 'FDDA_END', 'FEEDBACK', 'FGDT', 'FILEDESC', 'FLAG_CANFRA', 'FLAG_CLAYFRAC', 'FLAG_EROD', 'FLAG_EXCLUDED_MIDDLE', 'FLAG_FMEP', 'FLAG_FRC_URB2D', 'FLAG_IMPERV', 'FLAG_LAI12M', 'FLAG_LAKE_DEPTH', 'FLAG_METGRID', 'FLAG_MF_XY', 'FLAG_PSFC', 'FLAG_SANDFRAC', 'FLAG_SLP', 'FLAG_SM000010', 'FLAG_SM010040', 'FLAG_SM040100', 'FLAG_SM100200', 'FLAG_SNOW', 'FLAG_SNOWH', 'FLAG_SOILCAT', 'FLAG_SOILHGT', 'FLAG_SOIL_LAYERS', 'FLAG_ST000010', 'FLAG_ST010040', 'FLAG_ST040100', 'FLAG_ST100200', 'FLAG_URB_PARAM', 'FLAG_VAR_SSO', 'FLAG_VEGCAT', 'FTYPE', 'GDNAM', 'GDTYP', 'GFDDA_END_H', 'GFDDA_INTERVAL_M', 'GHG_INPUT', 'GMT',
    //     'GQ', 'GRAV_SETTLING', 'GRIDTYPE', 'GRID_FDDA', 'GRID_ID', 'GRID_SFDDA', 'GT', 'GUV', 'GWD_OPT', 'HISTORY', 'HYBRID_OPT', 'HYPSOMETRIC_OPT', 'ICLOUD', 'ICLOUD_CU', 'IDCOR', 'IDEAL_CASE', 'IF_RAMPING', 'IOAPI_VERSION', 'ISFFLX', 'ISFTCFLX', 'ISHALLOW', 'ISICE', 'ISLAKE', 'ISOILWATER', 'ISURBAN', 'ISWATER', 'I_PARENT_START', 'JULDAY', 'JULYR', 'J_PARENT_START', 'KHDIF', 'KM_OPT', 'KVDIF', 'MAP_PROJ', 'MAP_PROJ_CHAR', 'MFSHCONV', 'MMINLU', 'MOAD_CEN_LAT', 'MOIST_ADV_OPT', 'MP_PHYSICS', 'Model', 'NCO', 'NCOLS', 'NLAYS', 'NLayers', 'NROWS', 'NTASKS_TOTAL', 'NTASKS_X', 'NTASKS_Y', 'NTHIK', 'NUM_LAND_CAT', 'NUM_METGRID_SOIL_LEVELS', 'NVARS', 'OBS_COEF_MOIS', 'OBS_COEF_PSTR', 'OBS_COEF_TEMP', 'OBS_COEF_WIND', 'OBS_DTRAMP', 'OBS_IDYNIN', 'OBS_IONF', 'OBS_NUDGE_MOIS', 'OBS_NUDGE_OPT', 'OBS_NUDGE_PSTR', 'OBS_NUDGE_TEMP', 'OBS_NUDGE_WIND', 'OMLCALL', 'OPT_ALB', 'OPT_BTR', 'OPT_CROP', 'OPT_CRS', 'OPT_FRZ', 'OPT_GLA', 'OPT_INF', 'OPT_PEDO', 'OPT_RAD', 'OPT_RSF', 'OPT_RUN', 'OPT_SFC', 'OPT_SNF', 'OPT_SOIL', 'OPT_STC', 'OPT_TBOT', 'PARENT_GRID_RATIO', 'PARENT_ID', 'POLE_LAT', 'POLE_LON', 'PREC_ACC_DT', 'P_ALP', 'P_BET', 'P_GAM', 'RADT', 'RA_LW_PHYSICS', 'RA_SW_PHYSICS', 'SCALAR_ADV_OPT', 'SCALAR_PBLMIX', 'SDATE', 'SF_LAKE_PHYSICS', 'SF_OCEAN_PHYSICS', 'SF_SFCLAY_PHYSICS',
    //     'SF_SURFACE_MOSAIC', 'SF_SURFACE_PHYSICS', 'SF_URBAN_PHYSICS', 'SGFDDA_END_H', 'SGFDDA_INTERVAL_M', 'SHCU_PHYSICS', 'SIMULATION_INITIALIZATION_TYPE', 'SIMULATION_START_DATE', 'SKEBS_ON', 'SMOOTH_OPTION', 'SOUTH-NORTH_GRID_DIMENSION', 'SOUTH-NORTH_PATCH_END_STAG', 'SOUTH-NORTH_PATCH_END_UNSTAG', 'SOUTH-NORTH_PATCH_START_STAG', 'SOUTH-NORTH_PATCH_START_UNSTAG', 'SPEC_BDY_FINAL_MU', 'SST_UPDATE', 'STAND_LON', 'START_DATE', 'STIME', 'SURFACE_INPUT_SOURCE', 'SWINT_OPT', 'SWRAD_SCAT', 'StartDate', 'Start_Date', 'Start_Time', 'TITLE', 'TKE_ADV_OPT', 'TRACER_PBLMIX', 'TRUELAT1', 'TRUELAT2', 'TSTEP', 'Title', 'UPNAM', 'USE_MAXW_LEVEL', 'USE_Q_DIABATIC', 'USE_THETA_M', 'USE_TROP_LEVEL', 'VAR-LIST', 'VGLVLS', 'VGTOP', 'VGTYP', 'Version', 'WDATE', 'WEST-EAST_GRID_DIMENSION', 'WEST-EAST_PATCH_END_STAG', 'WEST-EAST_PATCH_END_UNSTAG', 'WEST-EAST_PATCH_START_STAG', 'WEST-EAST_PATCH_START_UNSTAG', 'WTIME', 'W_DAMPING', 'XCELL', 'XCENT', 'XORIG', 'YCELL', 'YCENT', 'YORIG', 'YSU_TOPDOWN_PBLMIX', '_NCProperties', 'att', 'att0', 'att1', 'att2', 'att3', 'att4', 'att5', 'attx', 'author', 'case', 'corner_lats', 'corner_lons', 'dx', 'dy', 'grid_id', 'gt', 'history', 'history_of_appended_files', 'host', 'i_parent_end', 'i_parent_start', 'initial_file', 'j_parent_end', 'j_parent_start', 'logname', 'longer_name', 'nco_openmp_thread_number', 'parent_grid_ratio', 'parent_id', 'plugh', 'proj4', 'revision_Id', 'source', 'sr_x', 'sr_y', 'time', 'title', 'topography_file', 'wkt', 'x0', 'y0',
    //     'yet_another_attribute'];
    const attributeList = []


    let temp = { fieldName: 'VAR', varName: '', statsValue: 'stat', operator: 'op', fieldValue: '' }
    const [components, setComponents] = useState([{ ...temp }]);
    const [items, setItems] = useState(variableList);

    const handleAddComponent = (index) => {
        const newComponents = [...components];
        newComponents.splice(index + 1, 0, { ...temp, input1: '' }); // Adding an object with multiple input fields
        setComponents(newComponents);
    };

    const handleChange = (index, field, value) => {
        const updatedComponents = [...components];
        updatedComponents[index] = { ...components[index], [field]: value };
        setComponents(updatedComponents);
    };

    const handleToggle = (index, toggleVal) => {
        handleChange(index, "fieldName", toggleVal === "VAR" ? "ATTR" : "VAR")
        if (toggleVal === "VAR") {
            setItems(attributeList)
        } else {
            setItems(variableList)
        }
    }

    const handleDeleteComponent = (index) => {
        const updatedComponents = components.filter((_, i) => i !== index);
        setComponents(updatedComponents);
    };

    const handleSearch = async () => {
        let searchQuery = components.map((item, index) => {
            return `${item.fieldName}.${item.varName}.${item.statsValue} ${item.operator} ${item.fieldValue}`
        }).join(" AND ");
        dispatch(addQuery(searchQuery))
    }

    return (
        <div className="flex flex-col content-between flex-wrap">
            <div className='flex flex-col gap-4'>
                {components.map((component, index) => (
                    <Predicate
                        key={index}
                        component={component}
                        onChange={(field, value) => handleChange(index, field, value)}
                        onAdd={() => handleAddComponent(index)}
                        onDelete={() => handleDeleteComponent(index)}
                        onToggle={(toggleVal) => handleToggle(index, toggleVal)}
                        items={items}
                    />
                ))}
            </div>
            <button className="btn mt-4" onClick={handleSearch}>Search</button>
        </div>
    );
}
export default Filter;